### ISSUE TITLE
AWS-S3 dashboard

### ISSUE THREAD

**Issue by ruabr** [dfds/ded-grafana-dashboards#29]
- [x] size
- [x] bucket names
- [x] object files
- ~~last modified (not possible via CloudWatch)~~
- [x] errors

**Comment by samidbb** [comment]
Requests doesn't show up - returns with ajax error
last modified not possible using cloudwatch
list of bucket names not possible to get as table

**Comment by rifisdfds** [comment]
I have added a list of bucket names to the dashboard into a table as this is possible. I have also added their names to the storage metrics graphs and hidden variable options at the top that are not appropriate to be changed by user with current working graphs.

The other 2 look like Sami is correct:
- No values returned for any of the Request Metrics, although documentation says there sholuld be. This might require some further investigation at a later point
- Last modified is not a available in any metric

I suggest we remove the Request graphs from the bottom of the dashboard. I will put this into needs review, let me know if you agree

**Comment by rifisdfds** [comment]
Investigation into Request Metrics has shown that these need enabling per-bucket. For now we have enabled for the k8s bucket, but we need a team decision on whether to enable them on all buckets or a select few

**Comment by samidbb** [comment]
Bars vs Graphs
Do we need to enable request metrics on each bucket?

**Comment by jandr-dfds** [comment]
The following chart seems to not be working in prod:

- filtered requests
- filtered latency
- filtered bytes
- filtered errors

**Comment by rifisdfds** [comment]
@jandr-dfds We have only enabled those metrics in playground for now to assess the costs (we should have made a note in here) so we can make a decision as per previous comments. They won't work in non-prod or prod yet

**Comment by rifisdfds** [comment]
Please review the dashboard in Playground only, it is the only environment that has Request metrics enabled on any S3 bucket - https://dashboard.ded.dfds.cloud/d/9n9v_icik/aws-s3?refresh=30s&orgId=1

To expand on Sami's comment above:

We would like opinion on the bar chart vs the graph or use both complimenting each other (see Bucket Size Bytes and Bucket Size Bytes (History)) so we can apply it and the same to Number of Objects

We would also like everyone's opinion on what S3 buckets we should enable Request metrics on so that we can come to an agreement. Should we:
- Periodically search for all S3 buckets in the account and enable Request metrics
- Enable Request metrics on a case by case basis at creation

My own thoughts are that we shouldn't enable it on all S3 buckets as there will likely be some we don't care about and this would be a waste of money. I think we should retrospectively enable it for the things we care about (ie the k8s bucket, elasticsearch) and if we want the metrics on anything going forward we need to enable it via pipeline at creation

When we have reached a decision we can make a new task to enable the metrics however we agree

**Comment by ruabr** [comment]
Doesnt seem useful. Maybe delete at some point
