### ISSUE TITLE
AWS Cost overview dashboard

### ISSUE THREAD

**Issue by ruabr** [dfds/ded-grafana-dashboards#33]
* Billing info per account
* Billing info totally
* Billing per service in AWS (if possible)
* Projections (PromQL)

**Comment by rifisdfds** [comment]
I am placing this for review:

Billing info per account is achieved (providing we are only interested in our accounts) because the dashboard uses the CloudWatch datasource already setup in each environment.

Billing info totally is achieved (per prod, non-prod and playground) with a current spend singlestat

Billing per service is achieved with a graph on the main page plus a drop down for singlestat

Projections is not achieved, I cannot see how to do this with a CloudWatch data source.

If we need to look at all accounts in across our organisation then we will need to add a new DataSource pointing to our top-level account and investigate using the LinkedAccount dimension, but I will leave this to pick up as an extra if time permits. Please let me know if you think this is worth pursuing or not.

I'm not sure whether to remove "Selected Service Cost" as it is in error until you select a Service from the drop down which i don't like. I can't see how to work around it nicely, so would like your thoughts

**Comment by raras-dfds** [comment]
I'd suggest last 30 days (or even 3 months), instead of month to date. Otherwise it will be of little value the first week's time each month, and be difficult to compare expense to history.

Now that we have added a CloudWatch datasource for master AWS account, you can graph the overall cost, instead of cost for the particular account (if you prefer).

**Comment by rifisdfds** [comment]
I have changed now to make use of the master account for cloudwatch. I have split the dashboard into 2 parts to allow better view of each account's costs.

i don't like it much, but i think the only alternative is to have a row for each account with a graph of services in and that would be harder to maintain. at least with this way there is only one graph to edit across all the accounts

it would be much nicer if you could get the account name back with the account number but i've had to make a manual list that you can click on the left to see the breakdown for that account

**Comment by ruabr** [comment]
Looks great based on the data we have available. Might need to revisit it in the future when we have some more specific requirements than "a cost overview"

**Comment by TryTryAgain** [comment]
@rifisdfds care to share your solution for "mak[ing] a manual list that you can click on the left to see the breakdown for that account"?
