### ISSUE TITLE
Get notified of failing k8s nodes in slack

### ISSUE THREAD

**Issue by ruabr** [dfds/ded-grafana-dashboards#39]

**Comment by ruabr** [comment]
I believe this should work: sum(up{kubernetes_io_role="node", job="kubernetes-nodes"}) by (instance) < 1
If the timeserie is present it will get auto populated with 0's if the node is missing at scape time

**Comment by rifisdfds** [comment]
I already have a working query which is simply:

`up{job="kubernetes-nodes"} != 1`

No need for SUM and It will also include master nodes as it is not filtering by role

Along with the config:

`summary: "{{ $labels.kubernetes_io_role }} {{ $labels.instance }} is down in {{ $labels.environment }} \n"`

the alert displays:

> node ip-172-20-37-161.eu-west-2.compute.internal is down in
> master ip-172-20-63-108.eu-west-2.compute.internal is down in

However, the $labels.environment comes through as blank. This label is set in the alert config:

```
labels:
  severity: alert
  environment: 'RF-Cluster'
```
And shows in the alert in AlertManager. However, it does not show in Slack as you can see above.

@ruabr If you can spare some time to help me figure it out that would be great, otherwise we can fall back to relying on just a simple picture/icon in slack to differentiate the environments as I don't want to spend too much more time on it

**Comment by rifisdfds** [comment]
Done
