### ISSUE TITLE
Get notified in slack when resources in k8s becomes low

### ISSUE THREAD

**Issue by ruabr** [dfds/ded-grafana-dashboards#40]
Check for RAM and CPU

**Comment by rifisdfds** [comment]
@samdi-dfds I've replaced the rules you've made for these so that they treat node/master (and filesystem devices in the case of the disk space alerts) individually rather than as a collective which I think is more appropriate for alerting.

i have left the old ones commented out. perhaps we can go over them on monday if you'd like to see?

**Comment by rifisdfds** [comment]
I would like some more alerts, such as Kubernetes API latency, Kubernetes version mismatch etc, predictions using predict_linear but technically the requirements for this are done now so closing
